apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: altshare-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      try_files $uri $uri/ /index.html;
spec:
  ingressClassName: public
  rules:
  - host: share.3xjn.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: altshare-ui
            port:
              number: 80
  tls:
  - hosts:
    - share.3xjn.dev
    secretName: altshare-ui-tls-cert
